name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Download FRP
      run: Invoke-WebRequest -Uri https://github.com/fatedier/frp/releases/download/v0.43.0/frp_0.43.0_windows_amd64.zip -OutFile frp.zip

    - name: Extract FRP
      run: Expand-Archive -Path frp.zip -DestinationPath ./frp

    - name: Verify FRP Files
      run: Get-ChildItem -Path ./frp  # List extracted files to verify that frpc.exe exists

    - name: Create FRP Config
      run: |
        Set-Content -Path ./frp/frpc.ini -Value "[common]"
        Add-Content -Path ./frp/frpc.ini -Value "server_addr = YOUR_FRP_SERVER_ADDRESS"
        Add-Content -Path ./frp/frpc.ini -Value "server_port = YOUR_FRP_SERVER_PORT"
        Add-Content -Path ./frp/frpc.ini -Value "[rdp]"
        Add-Content -Path ./frp/frpc.ini -Value "type = tcp"
        Add-Content -Path ./frp/frpc.ini -Value "local_port = 3389"
        Add-Content -Path ./frp/frpc.ini -Value "remote_port = YOUR_PUBLIC_PORT"

    - name: Run FRP Client
      run: Start-Process -NoNewWindow -FilePath "$PWD/frp/frpc.exe" -ArgumentList '-c $PWD/frp/frpc.ini' -PassThru | Out-Null

    - name: Keep-Alive Loop
      run: |
        $minutes = 0
        while ($minutes -lt 1440) {
          Write-Host "Still alive... $minutes minutes passed"
          Start-Sleep -Seconds 60
          $minutes++
