name: Keep ngrok Alive

on:
  push:
    branches:
      - main

jobs:
  keep-ngrok-alive:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Enable RDP User
        run: |
          $username = "moha"
          $password = "qpqp112233@1"
          $secpasswd = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name $username -Password $secpasswd -FullName "RDP User" -Description "User for Remote Desktop access"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

      - name: Download ngrok
        run: Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip

      - name: Unzip ngrok
        run: Expand-Archive -Path ngrok.zip -DestinationPath .\ngrok

      - name: Add ngrok Auth Token
        run: .\ngrok\ngrok.exe config add-authtoken 2V4ZVr5efWMydD5SRyvxg48Q73t_25NK2LtPxxtDFsMxQzjv6

      - name: Keep ngrok Alive
        run: |
          $ngrokPath = ".\ngrok\ngrok.exe"
          $port = 3389

          function Start-Ngrok {
              Start-Process -NoNewWindow -FilePath $ngrokPath -ArgumentList "tcp $port"
          }

          Start-Ngrok
          Start-Sleep -Seconds 21600

          while ($true) {
              $ngrokProcess = Get-Process ngrok -ErrorAction SilentlyContinue
              if (-not $ngrokProcess) {
                  Start-Ngrok
              }
              Start-Sleep -Seconds 21600
          }
