name: Setup Windows RDP with ngrok

on:
  push:
    branches:
      - main

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable Remote Desktop
        run: |
          # Enable RDP
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          # Update registry to allow RDP connections
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0

      - name: Create User for RDP
        run: |
          $username = "moha"
          $password = ConvertTo-SecureString "moha" -AsPlainText -Force
          New-LocalUser -Name $username -Password $password -FullName "RDP User" -Description "User for Remote Desktop access"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
          
      - name: Start RDP Service
        run: |
          Start-Service TermService

      - name: Install ngrok
        run: |
          # Download and extract ngrok
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath .\ngrok
          Remove-Item ngrok.zip

      - name: Start ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}  # Ensure this secret is set
        run: |
          # Check if the NGROK_AUTH_TOKEN is set
          if (-not $env:NGROK_AUTH_TOKEN) {
            Write-Host "Error: NGROK_AUTH_TOKEN is not set!"
            exit 1
          }
          .\ngrok\ngrok.exe authtoken $NGROK_AUTH_TOKEN
          Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp 3389"
          
      - name: Output ngrok Info
        run: |
          # Wait for ngrok to establish a connection
          Start-Sleep -Seconds 10
          # Retrieve the public ngrok URL
          $ngrokInfo = Invoke-RestMethod http://localhost:4040/api/tunnels
          Write-Host "RDP is accessible at: $($ngrokInfo.tunnels[0].public_url)"
