name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360  # Maximum timeout allowed by GitHub Actions

    steps:
    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - name: Enable Firewall Rule for RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Enable RDP User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Admin Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Install OpenSSH Server
      run: Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

    - name: Start OpenSSH Server
      run: Start-Service sshd

    - name: Set SSH Service to Start on Boot
      run: Set-Service -Name sshd -StartupType 'Automatic'

    - name: Allow SSH in Firewall
      run: New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22

    - name: Display SSH Information
      run: hostname

    - name: Keep-Alive Loop
      run: |
        $minutes = 0
        while ($minutes -lt 1440) {
          Write-Host "Still alive... $minutes minutes passed"
          Start-Sleep -Seconds 60
          $minutes++
