name: Setup RDP

on: [push]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Enable RDP
      run: |
        $username = "moha"
        $password = "qpqp112233@1"
        New-LocalUser -Name $username -Password (ConvertTo-SecureString $password -AsPlainText -Force) -FullName "RDP User" -Description "User for Remote Desktop access"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
        Start-Service TermService

    - name: Download ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
        Expand-Archive -Path ngrok.zip -DestinationPath .\ngrok
        Remove-Item ngrok.zip

    - name: Setup ngrok
      run: |
        .\ngrok\ngrok.exe config add-authtoken 2V4ZVr5efWMydD5SRyvxg48Q73t_25NK2LtPxxtDFsMxQzjv6
        .\ngrok\ngrok.exe tcp 3389

    - name: Start RDP
      run: |
        Start-Service TermService
