name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download AnyDesk
      run: Invoke-WebRequest https://download.anydesk.com/AnyDesk.exe -OutFile AnyDesk.exe

    - name: Install AnyDesk
      run: Start-Process -FilePath AnyDesk.exe -ArgumentList "/S" -Wait

    - name: Start AnyDesk
      run: Start-Process "C:\Program Files (x86)\AnyDesk\AnyDesk.exe"

    - name: Get AnyDesk ID
      run: |
        # Wait for AnyDesk to start
        Start-Sleep -Seconds 5
        # Get the AnyDesk ID
        $anyDeskID = (Get-Content "C:\ProgramData\AnyDesk\ad.cache" | Select-String -Pattern "Identity" | ForEach-Object { $_ -replace '.*?Identity: ', '' })
        Write-Host "AnyDesk ID: $anyDeskID"
