name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Node.js and LocalTunnel
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install -g localtunnel

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Local User Password
      run: |
        $user = "runneradmin"
        $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name $user -Password $password

    - name: Run LocalTunnel and Display URL
      run: |
        $output = & node -e "require('child_process').exec('lt --port 3389', (error, stdout, stderr) => { if (error) throw error; console.log(stdout); });"
        Write-Host "Your LocalTunnel URL: $output"

    - name: Keep Tunnel Alive
      run: Start-Sleep -Seconds 86400  # Keep the tunnel alive for 24 hours
