name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Playit.gg Client
      run: |
        Invoke-WebRequest https://playit.gg/downloads/playit-client.exe -OutFile playit-client.exe

    - name: Install and Configure Playit.gg Tunnel
      run: |
        Start-Process -NoNewWindow -FilePath "playit-client.exe" -ArgumentList "service install"
        Start-Sleep -Seconds 5
        Start-Process -NoNewWindow -FilePath "playit-client.exe" -ArgumentList "service start"

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Local User Password
      run: |
        $user = "runneradmin"
        $password = ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force
        Set-LocalUser -Name $user -Password $password

    - name: Keep Tunnel Alive
      run: Start-Sleep -Seconds 86400  # Keep the tunnel alive for 24 hours
