name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
    - name: Download FRP
      run: Invoke-WebRequest -Uri https://github.com/fatedier/frp/releases/download/v0.43.0/frp_0.43.0_windows_amd64.zip -OutFile frp.zip

    - name: Extract FRP
      run: Expand-Archive -Path frp.zip -DestinationPath ./frp

    - name: Create FRP Config
      run: |
        echo [common] > ./frp/frpc.ini
        echo server_addr = <YOUR_FRP_SERVER_ADDRESS> >> ./frp/frpc.ini
        echo server_port = <YOUR_FRP_SERVER_PORT> >> ./frp/frpc.ini
        echo [rdp] >> ./frp/frpc.ini
        echo type = tcp >> ./frp/frpc.ini
        echo local_port = 3389 >> ./frp/frpc.ini
        echo remote_port = <YOUR_PUBLIC_PORT> >> ./frp/frpc.ini

    - name: Run FRP Client
      run: Start-Process -NoNewWindow -FilePath .\frp\frpc.exe -ArgumentList '-c ./frp/frpc.ini' -PassThru | Out-Null

    - name: Keep-Alive Loop
      run: |
        $minutes = 0
        while ($minutes -lt 1440) {
          Write-Host "Still alive... $minutes minutes passed"
          Start-Sleep -Seconds 60
          $minutes++
